//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoservisRKS_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizacijskiToken
    {
        public int AutorizacijskiTokenID { get; set; }
        public string Vrijednost { get; set; }
        public Nullable<int> KlijentID { get; set; }
        public Nullable<System.DateTime> VrijemeEvidentiranja { get; set; }
        public string IpAdresa { get; set; }
        public string DeviceInfo { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
    }
}
