//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoservisRKS_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AutoservisRKSEntities : DbContext
    {
        public AutoservisRKSEntities()
            : base("name=AutoservisRKSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutorizacijskiToken> AutorizacijskiToken { get; set; }
        public virtual DbSet<Klijenti> Klijenti { get; set; }
        public virtual DbSet<Ponude> Ponude { get; set; }
        public virtual DbSet<Upiti> Upiti { get; set; }
    
        public virtual ObjectResult<AutorizacijskiToken> GetTokenPoVrijednosti(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AutorizacijskiToken>("GetTokenPoVrijednosti", tokenParameter);
        }
    
        public virtual ObjectResult<AutorizacijskiToken> GetTokenPoVrijednosti(string token, MergeOption mergeOption)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AutorizacijskiToken>("GetTokenPoVrijednosti", mergeOption, tokenParameter);
        }
    }
}
